# Generated by Django 6.0.6 on 2026-06-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['added_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='place',
            name='artwork_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='place',
            name='visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='external_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_visited'], name='planner_pla_is_visi_b0078b_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['external_id'], name='planner_pla_externa_2371ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('project', 'external_id'), name='unique_project_place'),
        ),
    ]
